import AuthProvider from '@/components/AuthProvider'
import Footer from '@/components/Footer'
import Navbar from '@/components/Navbar'
import Notifications from '@/components/Notifications'
import ReduxProvider from '@/redux/ReduxProvider'
import { Inter } from 'next/font/google'
import { ToastContainer } from 'react-toastify'
// import 'react-toastify/dist/ReactToastiy.css'
import "react-toastify/dist/ReactToastify.css"
import './globals.css'
const inter = Inter({ subsets: ['latin'] })
export const metadata = {
  title: 'Comfortable Shoe Store',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReduxProvider>
          <AuthProvider>
            <div>
              <Notifications />
              <Navbar/>
              {children}
              <Footer />
              <ToastContainer
                position="top-right"
                autoClose={3000}
                closeOnClick
                theme="dark"
              />
            </div>
            
          </AuthProvider>
        </ReduxProvider>
        
        </body>
    </html>
  )
}
