
import { Poppins } from 'next/font/google'
import { ThemeProvider } from '../ThemeContex/ThemeContex'
import Sidebar from '../components/Sidebar'
import './globals.css'

const poppins = Poppins({
  weight: ['400','600','700'],
  subsets: ['latin'],
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.className}>
       <ThemeProvider>
        <div className='dark:bg-dark dark:text-textPrimary h-screen w-full transition-all duration-200'>
        {/* <Navbar/> */}
          <div className='flex'>
            <Sidebar />
            <div>
              {children}
            </div>
          </div>
        </div>
       </ThemeProvider>
        </body>
    </html>
  )
}
